CREATE TABLE IF NOT EXISTS VOTANT (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	X INT,
	Y INT
	);


CREATE TABLE IF NOT EXISTS CANDIDAT (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	NOM VARCHAR(20),
	X INT,
	Y INT,
	VISIBILITE NUMERIC(3,2),
	SEXE CHAR,
	AGE INT
	);

CREATE TABLE IF NOT EXISTS PERSONNE (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	X INT,
	Y INT,
	COMPETENCE FLOAT,
	POIDS INT,
	DELEGATION BOOLEAN
	);

CREATE TABLE IF NOT EXISTS CONTRAINTES_INVIDIVIDUELLES(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	NOM_MIN VARCHAR(20),
	NOM_MAX VARCHAR(20),
	X_MIN INTEGER,
	X_MAX INTEGER,
	Y_MIN INTEGER,
	Y_MAX INTEGER,
	VISIBILITE_MIN NUMERIC(3,2),
	VISIBILITE_MAX NUMERIC(3,2),
	SEXE CHAR,
	AGE_MIN INTEGER,
	AGE_MAX INTEGER
);

CREATE TABLE IF NOT EXISTS CONTRAINTES_GLOBALES(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	PARITE_F NUMERIC(3,2),
	PARITE_H NUMERIC(3,2),
	DISTANCE_MIN NUMERIC(3,2),
	DISTANCE_MAX NUMERIC(3,2)
);

